### ISSUE TITLE
FollowStore and CommentStore may not be necessary

### ISSUE THREAD

**Issue by rglassett** [billylittlefield/JoggerLogger#2]
Depending on where and how you plan to display follows and comments, I think you won't need these stores. You should be able to include the relevant data in the JSON response sent to your workouts' ApiUtil.

For follows, include the `id` of the Follow associated with the current user and workout. If it's nil, your button can create a like; if it's an integer, the button can destroy the like with that id.

Comments can just be an array; your Workout component can have nested Comment components for each of these.

**Comment by billylittlefield** [comment]
This was correct!
