### ISSUE TITLE
Schema issues

### ISSUE THREAD

**Issue by rglassett** [billylittlefield/JoggerLogger#3]
Should `workouts.pace` be a column, or could it be calculated from `workouts.miles / workouts.time`?

How will team workouts be handled? Will we be able to see all the workouts for all members of that team? Or should workouts be implemented with a polymorphic association? Maybe a join table for WorkoutParticipations?

**Comment by billylittlefield** [comment]
Pace can definitely be calculated -- I was thinking it might be easier to just have direct access to a column for it, but if a user is updating miles or time it might be easier to have pace calculated on the spot than also having to change pace.

At this point I wasn't planning on implementing a 'team workout' feature -- Team is just an interface to see the calendars for all team members in one place, but they're still unique to the members. Being able to tag other users in a workout so it auto fills their calendar might be a bonus feature I add to the list if I can get everything else done in time.
